version: "3"
services:
  influxdb:
    image: influxdb:1.4.2
    volumes:
      - influxdb:/var/lib/influxdb

  mongo:
    image: mongo:4.1.10
    volumes:
      - mongo:/data/db

  rabbitmq:
    image: pedroalvesferreira/rabbitmq-with-web-mqtt
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"

  listserver:
    build: ./server/
    ports:
      - "8080"
      - "3030"
    environment:
        - EBU_LIST_WEB_APP_DOMAIN=${EBU_LIST_WEB_APP_DOMAIN}
        - EBU_LIST_LIVE_MODE=${EBU_LIST_LIVE_MODE}
    links:
      - influxdb
      - mongo
      - rabbitmq
    volumes:
      - ${EBU_LIST_HOST_DATA_FOLDER:-listserver}:/home/
  
  listreverseproxy:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - listserver
    volumes:
      - ./data/config:/etc/nginx
      - ./data/certs:/etc/ssl/certs
      - ./data/log/nginx:/var/log/nginx/
      
volumes:
  mongo:
  listserver:
  influxdb:
