# Configurations for LIST Web Server
# Use this file for development mode

# Filesystem related
folder: /home/
cpp: /app/bin/

# HTTP-related
cookieSecret: STRD4O
webappDomain: http://localhost:8080

# MongoDB database
database:
  hostname: mongo
  port: 27017

# InfluxDB URL
influx:
  hostname: influxdb
  port: 8086
