probe:
  # change this to a new UUID
  id: 6cbf09dc-e602-45ee-9c70-0a0b3b1cf16e
  label: "LIST capture probe #1"

rabbitmq:
  hostname: localhost
  port: 5672

###############################################################################
# Uncomment this section to use "capture" to performe the capture

# recorder:
#  # The interface to use for capture
#  interface: enp64s0f0

###############################################################################
# Uncomment this section to use "tcpdump" to performe the capture

#tcpdump:
 # The interface to use for capture
 #interface: enp64s0f0

 ###############################################################################
# Uncomment this section to upload a pre-recorded file rather than capturing

dummy_pcap: ../../js/tests/pcaps/eemebe_t_1080i59.pcap
