# Configurations for LIST Web Server
# Use this file for development mode

# Filesystem related
folder: /home/ebu/tmp/list/
cpp: /home/ebu/list/live/cmake-build-debug/third_party/ebu_list/bin/

# HTTP-related
cookieSecret: STRD4O
#webappDomain: https://localhost
#apiUrl: http://localhost:3030

# MongoDB database
database:
  hostname: localhost
  port: 27017

# InfluxDB URL
influx:
  hostname: localhost
  port: 8086

# RabbitMQ
rabbitmq:
  hostname: localhost
  port: 5672
